openapi: 3.0.0
info:
  title: Instal API
  version: 1.0.0
  description: Secure API for client management with authentication and rate limiting
security:
  - apiKey: []
paths:
  /clients:
    post:
      summary: Create a new client
      description: Creates a new client with validated input data
      security:
        - apiKey: []
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e607k429lt9lqo0dkj
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
      x-yc-apigateway-rate-limits:
        - action: DENY
          rate: 10
          unit: minute
      requestBody:
        description: Client details
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - full_name
                - contact_number
                - passport_number
              properties:
                user_id:
                  type: string
                  minLength: 1
                  maxLength: 50
                  pattern: "^[a-zA-Z0-9_-]+$"
                  description: Unique user identifier
                full_name:
                  type: string
                  minLength: 1
                  maxLength: 100
                  pattern: "^[a-zA-ZÀ-ÿ\\s\\'-]+$"
                  description: Full name of the client
                contact_number:
                  type: string
                  minLength: 10
                  maxLength: 20
                  pattern: "^\\+?[1-9]\\d{1,14}$"
                  description: Contact phone number
                passport_number:
                  type: string
                  minLength: 6
                  maxLength: 20
                  pattern: "^[A-Z0-9]+$"
                  description: Passport number (uppercase letters and numbers)
                address:
                  type: string
                  maxLength: 255
                  pattern: "^[a-zA-ZÀ-ÿ0-9\\s\\.,\\'-]*$"
                  description: Address (optional)
      responses:
        '201':
          description: Client created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Unique client ID
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: array
                    items:
                      type: string
        '401':
          description: Unauthorized - Invalid or missing API key
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '409':
          description: Client with passport number already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '429':
          description: Rate limit exceeded
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /clients/{id}:
    get:
      summary: Get a client by ID
      description: Retrieves client information by ID with proper validation
      security:
        - apiKey: []
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e8b3od95f0h2fiernq
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
      x-yc-apigateway-rate-limits:
        - action: DENY
          rate: 30
          unit: minute
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
          description: Client ID (UUID format)
      responses:
        '200':
          description: Client retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  user_id:
                    type: string
                  full_name:
                    type: string
                  contact_number:
                    type: string
                  passport_number:
                    type: string
                  address:
                    type: string
                    nullable: true
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid client ID format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Unauthorized - Invalid or missing API key
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Client not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '429':
          description: Rate limit exceeded
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication

x-yc-apigateway-cors:
  origin:
    - '*'
  methods:
    - GET
    - POST
    - OPTIONS
  headers:
    - Content-Type
    - X-API-Key
  maxAge: 86400 