openapi: 3.0.0
info:
  title: Instal API
  version: 1.0.0
  description: Secure API for client management with authentication and rate limiting
security:
  - bearerAuth: []
paths:
  /clients:
    post:
      summary: Create a new client
      operationId: create-client
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e607k429lt9lqo0dkj
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
    get:
      summary: List all clients
      operationId: list-clients
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e2hioa9nvq86e1fhtv
        service_account_id: ajevsnimu8g62t29vlad
  /clients/search:
    get:
      summary: Search for clients
      operationId: search-clients
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e46icm3kuqf5mshnbq
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
  /clients/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a client by ID
      operationId: get-client
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e8b3od95f0h2fiernq
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
    put:
      summary: Update a client
      operationId: update-client
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4egqldupji1j6a52h1v
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
    delete:
      summary: Delete a client
      operationId: delete-client
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4emvjk3b8bslg8tnibd
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
  /investors:
    post:
      summary: Create a new investor
      operationId: create-investor
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ej2auh8nuqd4ug07b4
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
    get:
      summary: List all investors
      operationId: list-investors
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e30o3lml4ur152tei1
        service_account_id: ajevsnimu8g62t29vlad
  /investors/search:
    get:
      summary: Search for investors
      operationId: search-investors
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4edkrcgp4spbhlhoirn
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
  /investors/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get an investor by ID
      operationId: get-investor
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ehnha81dhv1t61vb5h
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
    put:
      summary: Update an investor
      operationId: update-investor
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ekneiud8r8kmlv5gfp
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
    delete:
      summary: Delete an investor
      operationId: delete-investor
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e3j9imqjagflipespv
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
  /installments:
    post:
      summary: Create a new installment
      operationId: create-installment
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ejin4kah34cvt6mbt8
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
    get:
      summary: List all installments
      operationId: list-installments
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eji2a3n3b9kmgvkcni
        service_account_id: ajevsnimu8g62t29vlad
  /installments/search:
    get:
      summary: Search for installments
      operationId: search-installments
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4edfrgpjcc1ohgj6efo
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
  /installments/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get an installment by ID
      operationId: get-installment
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4etn874nnro96omhmdk
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'

    delete:
      summary: Delete an installment
      operationId: delete-installment
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e6t65nb39k5dksq7s7
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
  /installment-payments/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    put:
      summary: Update an installment payment
      operationId: update-installment-payment
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ec86pvqoqla7ck2qv7
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
  /auth/register:
    post:
      summary: Register a new user
      operationId: auth-register
      security: 
        - apiKey: []  # Auth endpoints still use API key
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e4t4mv875gkg24at8a
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
  /auth/login:
    post:
      summary: Login user
      operationId: auth-login
      security: 
        - apiKey: []  # Auth endpoints still use API key
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e8jcns4qe2bkvh7rvv
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
  /auth/refresh:
    post:
      summary: Refresh access token
      operationId: auth-refresh
      security: 
        - apiKey: []  # Auth endpoints still use API key
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4evah37mne0rubchbl8
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
  /auth/verify:
    post:
      summary: Verify JWT token
      operationId: auth-verify
      security: 
        - apiKey: []  # Auth endpoints still use API key
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ebrg3ucrog7lqe4egr
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
  /auth/user:
    get:
      summary: Get current user information
      operationId: auth-get-user
      security:
        - bearerAuth: []
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eni47g77jfmhonbhde
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
    put:
      summary: Update user profile
      operationId: auth-update
      security:
        - bearerAuth: []
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e5tijqfm1q7ikuj0c5
        service_account_id: ajevsnimu8g62t29vlad
        payload_format_version: '1.0'
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-yc-apigateway-cors:
  origin:
    - '*'
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  headers:
    - Content-Type
    - X-API-Key
    - Authorization
  maxAge: 86400 