import '../entities/wallet.dart';
import '../entities/wallet_balance.dart';
import '../entities/installment_allocation.dart';
import '../entities/investment_summary.dart';
import '../repositories/wallet_repository.dart';
import '../repositories/wallet_balance_repository.dart';
import '../repositories/installment_allocation_repository.dart';
import '../../core/money_utils.dart';

/// Service for calculating investment returns and profit distributions
/// following Islamic finance principles (profit-sharing, no interest)
/// 
/// Business Model:
/// 1. Investor provides initial capital (e.g., 1,000,000 RUB)
/// 2. User buys products using wallet funds and sells on installment
/// 3. Installment payments flow back to the same wallet
/// 4. Profit = Current Wallet Value - Initial Investment
/// 5. Profit is split by investor/user percentages
class InvestmentService {
  final WalletRepository walletRepository;
  final WalletBalanceRepository balanceRepository;
  final InstallmentAllocationRepository allocationRepository;

  InvestmentService({
    required this.walletRepository,
    required this.balanceRepository,
    required this.allocationRepository,
  });

  /// Calculate investment summary for an investor wallet
  /// This calculates profit based on wallet growth: Current Wallet Value - Initial Investment
  Future<InvestmentSummary> calculateInvestmentSummary({
    required String walletId,
    required String userId,
  }) async {
    // Get wallet details
    final wallet = await walletRepository.getWalletById(walletId, userId);
    if (wallet == null) {
      throw Exception('Wallet not found');
    }

    if (wallet.type != WalletType.investor) {
      throw ArgumentError('Wallet is not an investor wallet');
    }

    // Get current balance
    final balance = await balanceRepository.getWalletBalance(walletId, userId);
    if (balance == null) {
      throw Exception('Wallet balance not found');
    }

    // Get active allocations for this wallet (money currently used for installments)
    final allocations = await allocationRepository.getActiveWalletAllocations(walletId, userId);
    final totalAllocatedMinorUnits = allocations.fold<int>(
      0,
      (sum, allocation) => sum + allocation.amountMinorUnits,
    );

    // Calculate total wallet value (current balance + allocated funds)
    final totalWalletValueMinorUnits = balance.balanceMinorUnits + totalAllocatedMinorUnits;
    
    // Calculate total profit generated by this wallet
    final totalProfitMinorUnits = totalWalletValueMinorUnits - wallet.investmentAmountMinorUnits!;
    
    // Calculate investor's share of the profit
    final investorProfitShareMinorUnits = totalProfitMinorUnits > 0 
        ? MoneyUtils.calculatePercentage(totalProfitMinorUnits, wallet.investorPercentage!)
        : 0;

    // Expected returns = Initial Investment + Investor's Profit Share
    final expectedReturnsMinorUnits = wallet.investmentAmountMinorUnits! + investorProfitShareMinorUnits;

    // Calculate due amount based on return date
    final dueAmountMinorUnits = _calculateDueAmount(
      wallet,
      expectedReturnsMinorUnits,
      totalWalletValueMinorUnits,
    );

    return InvestmentSummary(
      walletId: walletId,
      totalInvestedMinorUnits: wallet.investmentAmountMinorUnits!,
      currentBalanceMinorUnits: balance.balanceMinorUnits,
      totalAllocatedMinorUnits: totalAllocatedMinorUnits,
      expectedReturnsMinorUnits: expectedReturnsMinorUnits,
      dueAmountMinorUnits: dueAmountMinorUnits,
      returnDueDate: wallet.investmentReturnDate,
      profitPercentage: wallet.investorPercentage!,
    );
  }

  /// Calculate profit distribution for all investor wallets
  /// Each wallet's profit is calculated independently based on its own growth
  Future<List<ProfitDistribution>> calculateProfitDistribution({
    required String userId,
  }) async {
    // Get all investor wallets
    final investorWallets = await walletRepository.getWalletsByType(userId, WalletType.investor);
    final distributions = <ProfitDistribution>[];

    for (final wallet in investorWallets) {
      if (wallet.status != WalletStatus.active) continue;

      // Get current balance and allocations
      final balance = await balanceRepository.getWalletBalance(wallet.id, userId);
      if (balance == null) continue;

      final allocations = await allocationRepository.getActiveWalletAllocations(wallet.id, userId);
      final totalAllocated = allocations.fold<int>(
        0,
        (sum, allocation) => sum + allocation.amountMinorUnits,
      );

      // Calculate total wallet value
      final totalWalletValue = balance.balanceMinorUnits + totalAllocated;
      
      // Calculate profit generated by this specific wallet
      final walletProfit = totalWalletValue - wallet.investmentAmountMinorUnits!;
      
      // Only include wallets that have generated profit
      if (walletProfit > 0) {
        // Calculate investor's share of this wallet's profit
        final investorProfitShare = MoneyUtils.calculatePercentage(
          walletProfit,
          wallet.investorPercentage!,
        );

        distributions.add(ProfitDistribution(
          walletId: wallet.id,
          walletName: wallet.name,
          investorPercentage: wallet.investorPercentage!,
          totalAllocatedMinorUnits: totalAllocated,
          profitShareMinorUnits: investorProfitShare,
          returnDueDate: wallet.investmentReturnDate,
          totalWalletValueMinorUnits: totalWalletValue,
          initialInvestmentMinorUnits: wallet.investmentAmountMinorUnits!,
        ));
      }
    }

    return distributions;
  }

  /// Calculate return on investment (ROI) for an investor wallet
  Future<double> calculateROI({
    required String walletId,
    required String userId,
  }) async {
    final summary = await calculateInvestmentSummary(
      walletId: walletId,
      userId: userId,
    );

    return summary.roiPercentage;
  }

  /// Get investment performance analytics for all investor wallets
  Future<InvestmentPerformance> getInvestmentPerformance(String userId) async {
    final investorWallets = await walletRepository.getWalletsByType(userId, WalletType.investor);
    final activeWallets = investorWallets.where((w) => w.status == WalletStatus.active).toList();

    if (activeWallets.isEmpty) {
      return InvestmentPerformance.empty();
    }

    int totalInvestedMinorUnits = 0;
    int totalCurrentValueMinorUnits = 0;
    int totalAllocatedMinorUnits = 0;
    int totalProfitMinorUnits = 0;
    int overdueInvestments = 0;
    int activeInvestments = 0;

    for (final wallet in activeWallets) {
      totalInvestedMinorUnits += wallet.investmentAmountMinorUnits ?? 0;

      final balance = await balanceRepository.getWalletBalance(wallet.id, userId);
      if (balance != null) {
        final allocations = await allocationRepository.getActiveWalletAllocations(wallet.id, userId);
        final walletAllocated = allocations.fold<int>(
          0,
          (sum, allocation) => sum + allocation.amountMinorUnits,
        );
        
        final walletValue = balance.balanceMinorUnits + walletAllocated;
        totalCurrentValueMinorUnits += walletValue;
        totalAllocatedMinorUnits += walletAllocated;
        
        // Calculate profit for this wallet
        final walletProfit = walletValue - (wallet.investmentAmountMinorUnits ?? 0);
        if (walletProfit > 0) {
          totalProfitMinorUnits += walletProfit;
        }
      }

      // Check if investment is overdue
      if (wallet.investmentReturnDate != null) {
        if (DateTime.now().isAfter(wallet.investmentReturnDate!)) {
          overdueInvestments++;
        } else {
          activeInvestments++;
        }
      }
    }

    return InvestmentPerformance(
      totalInvestorsCount: activeWallets.length,
      totalInvestedMinorUnits: totalInvestedMinorUnits,
      totalCurrentValueMinorUnits: totalCurrentValueMinorUnits,
      totalAllocatedMinorUnits: totalAllocatedMinorUnits,
      totalProfitMinorUnits: totalProfitMinorUnits,
      activeInvestmentsCount: activeInvestments,
      overdueInvestmentsCount: overdueInvestments,
    );
  }

  /// Get investors with upcoming return dates
  Future<List<UpcomingReturn>> getUpcomingReturns({
    required String userId,
    int daysAhead = 30,
  }) async {
    final investorWallets = await walletRepository.getWalletsByType(userId, WalletType.investor);
    final upcomingReturns = <UpcomingReturn>[];

    final cutoffDate = DateTime.now().add(Duration(days: daysAhead));

    for (final wallet in investorWallets) {
      if (wallet.status != WalletStatus.active || wallet.investmentReturnDate == null) {
        continue;
      }

      if (wallet.investmentReturnDate!.isBefore(cutoffDate)) {
        final summary = await calculateInvestmentSummary(
          walletId: wallet.id,
          userId: userId,
        );

        upcomingReturns.add(UpcomingReturn(
          walletId: wallet.id,
          walletName: wallet.name,
          returnDate: wallet.investmentReturnDate!,
          dueAmountMinorUnits: summary.dueAmountMinorUnits,
          isOverdue: DateTime.now().isAfter(wallet.investmentReturnDate!),
        ));
      }
    }

    // Sort by return date (overdue first, then by date)
    upcomingReturns.sort((a, b) {
      if (a.isOverdue && !b.isOverdue) return -1;
      if (!a.isOverdue && b.isOverdue) return 1;
      return a.returnDate.compareTo(b.returnDate);
    });

    return upcomingReturns;
  }

  /// Validate Islamic finance compliance for investment terms
  bool validateIslamicCompliance({
    required double investorPercentage,
    required double userPercentage,
    required DateTime returnDate,
  }) {
    // Check percentage sum equals 100%
    if (!MoneyUtils.percentagesSum100(investorPercentage, userPercentage)) {
      return false;
    }

    // Check percentages are valid
    if (!MoneyUtils.isValidPercentage(investorPercentage) || 
        !MoneyUtils.isValidPercentage(userPercentage)) {
      return false;
    }

    // Check return date is in future
    if (returnDate.isBefore(DateTime.now())) {
      return false;
    }

    return true;
  }

  /// Calculate due amount based on investment terms and current date
  int _calculateDueAmount(
    Wallet wallet,
    int expectedReturnsMinorUnits,
    int currentWalletValueMinorUnits,
  ) {
    if (wallet.investmentReturnDate == null) {
      return 0;
    }

    final now = DateTime.now();
    final returnDate = wallet.investmentReturnDate!;

    // If return date has passed, investor is due their expected returns
    if (now.isAfter(returnDate)) {
      return expectedReturnsMinorUnits;
    }

    // If return date is in future, no amount is due yet
    return 0;
  }
}

/// Profit distribution calculation result
class ProfitDistribution {
  final String walletId;
  final String walletName;
  final double investorPercentage;
  final int totalAllocatedMinorUnits;
  final int profitShareMinorUnits;
  final DateTime? returnDueDate;
  final int totalWalletValueMinorUnits;
  final int initialInvestmentMinorUnits;

  const ProfitDistribution({
    required this.walletId,
    required this.walletName,
    required this.investorPercentage,
    required this.totalAllocatedMinorUnits,
    required this.profitShareMinorUnits,
    this.returnDueDate,
    required this.totalWalletValueMinorUnits,
    required this.initialInvestmentMinorUnits,
  });

  /// Get total allocated amount in rubles
  double get totalAllocated => MoneyUtils.minorUnitsToRubles(totalAllocatedMinorUnits);

  /// Get profit share in rubles
  double get profitShare => MoneyUtils.minorUnitsToRubles(profitShareMinorUnits);

  /// Get total wallet value in rubles
  double get totalWalletValue => MoneyUtils.minorUnitsToRubles(totalWalletValueMinorUnits);

  /// Get initial investment in rubles
  double get initialInvestment => MoneyUtils.minorUnitsToRubles(initialInvestmentMinorUnits);

  /// Get total profit generated by wallet in rubles
  double get totalProfit => totalWalletValue - initialInvestment;

  /// Get user's profit share in rubles
  double get userProfitShare => totalProfit - profitShare;

  /// Get investor's total return (investment + profit share) in rubles
  double get investorTotalReturn => initialInvestment + profitShare;

  @override
  String toString() {
    return 'ProfitDistribution(wallet: $walletName, value: ${MoneyUtils.formatMinorUnits(totalWalletValueMinorUnits)}, profit: ${MoneyUtils.formatMinorUnits(profitShareMinorUnits)})';
  }
}

/// Investment performance analytics
class InvestmentPerformance {
  final int totalInvestorsCount;
  final int totalInvestedMinorUnits;
  final int totalCurrentValueMinorUnits;
  final int totalAllocatedMinorUnits;
  final int totalProfitMinorUnits;
  final int activeInvestmentsCount;
  final int overdueInvestmentsCount;

  const InvestmentPerformance({
    required this.totalInvestorsCount,
    required this.totalInvestedMinorUnits,
    required this.totalCurrentValueMinorUnits,
    required this.totalAllocatedMinorUnits,
    required this.totalProfitMinorUnits,
    required this.activeInvestmentsCount,
    required this.overdueInvestmentsCount,
  });

  factory InvestmentPerformance.empty() {
    return const InvestmentPerformance(
      totalInvestorsCount: 0,
      totalInvestedMinorUnits: 0,
      totalCurrentValueMinorUnits: 0,
      totalAllocatedMinorUnits: 0,
      totalProfitMinorUnits: 0,
      activeInvestmentsCount: 0,
      overdueInvestmentsCount: 0,
    );
  }

  /// Get total invested amount in rubles
  double get totalInvested => MoneyUtils.minorUnitsToRubles(totalInvestedMinorUnits);

  /// Get total current value in rubles
  double get totalCurrentValue => MoneyUtils.minorUnitsToRubles(totalCurrentValueMinorUnits);

  /// Get total allocated amount in rubles
  double get totalAllocated => MoneyUtils.minorUnitsToRubles(totalAllocatedMinorUnits);

  /// Get total profit in rubles
  double get totalProfit => MoneyUtils.minorUnitsToRubles(totalProfitMinorUnits);

  /// Calculate overall ROI percentage
  double get overallROI {
    if (totalInvestedMinorUnits == 0) return 0.0;
    return (totalProfitMinorUnits / totalInvestedMinorUnits) * 100.0;
  }

  /// Calculate utilization rate (allocated / current value)
  double get utilizationRate {
    if (totalCurrentValueMinorUnits == 0) return 0.0;
    return (totalAllocatedMinorUnits / totalCurrentValueMinorUnits) * 100.0;
  }

  @override
  String toString() {
    return 'InvestmentPerformance(investors: $totalInvestorsCount, invested: ${MoneyUtils.formatMinorUnits(totalInvestedMinorUnits)}, value: ${MoneyUtils.formatMinorUnits(totalCurrentValueMinorUnits)})';
  }
}

/// Upcoming investment return information
class UpcomingReturn {
  final String walletId;
  final String walletName;
  final DateTime returnDate;
  final int dueAmountMinorUnits;
  final bool isOverdue;

  const UpcomingReturn({
    required this.walletId,
    required this.walletName,
    required this.returnDate,
    required this.dueAmountMinorUnits,
    required this.isOverdue,
  });

  /// Get due amount in rubles
  double get dueAmount => MoneyUtils.minorUnitsToRubles(dueAmountMinorUnits);

  /// Get days until return (negative if overdue)
  int get daysUntilReturn => returnDate.difference(DateTime.now()).inDays;

  @override
  String toString() {
    return 'UpcomingReturn(wallet: $walletName, due: ${MoneyUtils.formatMinorUnits(dueAmountMinorUnits)}, date: $returnDate, overdue: $isOverdue)';
  }
}